### ISSUE TITLE
Red circle toggle

### ISSUE THREAD

**Issue by judg393** [loki79uk/FS22_LumberJack#11]
Hi Loki 

Quick question the red circle that deletes trees is there a way to toggle this having problems trying to delete pesky downberry trees in SR the hit boxes are tiny and I just can't get a circle to appear. sometimes I get lucky but mostly not just wondered if there was any tips. Regular trees I get the green circle fine so I guess it's probably giants coding of these trees as the real trees work fine! 

I thought I'd read holding left alt made the circle go red but that doesn't appear to work for me.

**Comment by loki79uk** [comment]
Sorry, it took me so long to get around to this - I was working on getting the latest UAL update out on ModHub.

I had a play around on the first downberry tree that I found near the spawn point on SilverRun, and it seems that it is easier to get a red ring when crouching - I think it is because this is closer to the base, and because it makes the view angle to the tree more perpendicular (see below):
![image](https://user-images.githubusercontent.com/76516343/213860337-514f7101-47bf-486c-acf9-2c15bfd5b0da.png)

Lumberjack does its own detection for the tree deletion.  You can see the detection area (white square) by editing `LumberJack.showDebug = true` on line 119 of the main lua file.

**Comment by judg393** [comment]
Thank you mate I'll give that a shot
